### PR TITLE
Rename the `MessageInEnvelopSerializer` to `MessageInEnvelopeSerializer`

### PR DESCRIPTION
**Pull request by cmodijk**
Fixed the typo in class name and add the old one for BC reasons https://github.com/SimpleBus/Serialization/issues/4

Also involves these merge requests:
* https://github.com/SimpleBus/SimpleBusBernardBundleBridge/pull/7
* https://github.com/SimpleBus/RabbitMQBundleBridge/pull/28
* https://github.com/SimpleBus/JMSSerializerBundleBridge/pull/6
* https://github.com/SimpleBus/docs/pull/38
* https://github.com/SimpleBus/Asynchronous/pull/10

### CODE REVIEW

**Comment by cmodijk** [comment]
@Nyholm Do you see any problem in merging this and al the related MR's?

**Comment by Nyholm** [comment]
I reviewed the linked PRs. I think it is a BC break updating the constructors in the bundle. Isn't it?

**Comment by cmodijk** [comment]
> I reviewed the linked PRs. I think it is a BC break updating the constructors in the bundle. Isn't it?

You are right, tnx for checking. I will revert these and create a new pull requests for the next major version

**Comment by Nyholm** [comment]
👍

**Comment by cmodijk** [comment]
I removed the `MessageInEnvelopSerializer` BC class as i'm going to bump the major version.

**Pull request merged**
